name: Deploy Datapack

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Pull changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Use password instead of key
          script: |
            cd C:\Users\wilhe\OneDrive\Dokument\GitHub\Multiverse-Mystery-Datapack
            "C:/Program/git/cmd/git" pull
            mkdir testifworki
            echo "Git pull successful"

      - name: Run Python script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Use password instead of key
          script: |
            cd C:\Users\wilhe\datapack
            echo "Current directory: $PWD"
            python datapack_creator.py
            echo "Python script execution successful"
